# Generated by Django 4.0.5 on 2022-06-23 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_created_at_remove_user_firstname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='how_did_you_hear_about_us',
            field=models.CharField(choices=[('Select', 'Select'), ('Whatsapp', 'Whatsapp'), ('Twitter', 'Twitter'), ('Instagram', 'Instagram'), ('A friend', 'A friend'), ('Our Team', 'Our Team')], max_length=300, null=True),
        ),
    ]
