# Generated by Django 4.0.5 on 2022-07-05 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
